Spring:
  datasource:
    hikari:
      jdbc-url: "jdbc:postgresql://localhost:5432/my_brik_database?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
      maximum-pool-size: 10
      driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: "jdbc:postgresql://localhost:5432/my_brik_database?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
    driver-class-name: org.postgresql.Driver

---

jwtconfig:
  secret: secretsecretsecretbrik
  expiration: 600000 # time in milliseconds, expiration time for Token