Spring:
  flyway:
    enabled: true
    ignore-missing-migrations: true
    locations: classpath:/migration
    baseline-on-migrate: true
    baseline-description: Flyway Scripts
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  datasource:
    hikari:
      jdbc-url: "jdbc:postgresql://localhost:5432/my_brik_database?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
      maximum-pool-size: 10
      driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: "jdbc:postgresql://localhost:5432/my_brik_database?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
    driver-class-name: org.postgresql.Driver

---

jwtconfig:
  secret: secretsecretsecretbrik
  expiration: 36000000 # time in milliseconds, expiration time for Token

---

amazon:
  images:
    s3: mybrikproject
    accessKeyId: someToken
    secretKey: password
    bucket: mybrikproject
    serverUrl: "https://mybrikproject.s3.eu-central-1.amazonaws.com"
    userFolder: goods
    region: eu-central-1
